DEBUG 2021-07-26 09:05:23.796 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-26 09:05:23.796 UTC: 	 Running on: Linux lxplus735.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-26 09:05:23.796 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-26 09:05:23.814 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-07-26 09:05:23.835 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-07-26 09:05:23.835 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-26 09:05:23.874 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-07-26 09:05:23.875 UTC: 	 Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
ERROR 2021-07-26 09:05:23.875 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
INFO 2021-07-26 09:05:23.878 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-07-26 11:59:23.604 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-26 11:59:23.604 UTC: 	 Running on: Linux lxplus713.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-26 11:59:23.604 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-26 11:59:23.605 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-07-26 11:59:23.606 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-07-26 11:59:23.606 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-26 11:59:23.607 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-07-26 11:59:23.607 UTC: 	 Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
ERROR 2021-07-26 11:59:23.607 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
INFO 2021-07-26 11:59:23.630 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-07-26 12:52:50.890 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-26 12:52:50.890 UTC: 	 Running on: Linux lxplus713.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-26 12:52:50.890 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-26 12:52:50.891 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-07-26 12:52:50.893 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-07-26 12:52:50.893 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-26 12:52:51.103 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-07-26 12:52:51.104 UTC: 	 Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
ERROR 2021-07-26 12:52:51.104 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/MWGR4/CMSSW_11_3_1_patch1/src/MuDPGAnalysis/crab_GEMMuonNTuplizerOverMC' already exists 
Please change the requestName in the config file
INFO 2021-07-26 12:52:51.108 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-07-27 14:04:19.607 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-27 14:04:19.607 UTC: 	 Running on: Linux lxplus797.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-27 14:04:19.607 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-27 14:04:19.612 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
ERROR 2021-07-27 14:04:19.637 UTC: 	 CRAB configuration file muDpgNtuples_cfg.py not found.
ERROR 2021-07-27 14:04:19.637 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file muDpgNtuples_cfg.py not found.
INFO 2021-07-27 14:04:19.658 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-07-27 14:45:41.169 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-27 14:45:41.169 UTC: 	 Running on: Linux lxplus797.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-27 14:45:41.169 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-27 14:45:41.185 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
DEBUG 2021-07-27 16:01:20.954 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-27 16:01:20.955 UTC: 	 Running on: Linux lxplus797.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-27 16:01:20.955 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-27 16:01:20.958 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-07-27 16:01:20.973 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-07-27 16:01:20.973 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-27 16:01:20.991 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-07-27 16:01:20.991 UTC: 	 Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-07-27 16:01:20.991 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-07-27 16:01:21.022 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-08-11 07:26:31.895 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-08-11 07:26:31.895 UTC: 	 Running on: Linux lxplus781.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-11 07:26:31.895 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-11 07:26:31.895 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
ERROR 2021-08-11 07:26:31.897 UTC: 	 CRAB configuration file M not found.
ERROR 2021-08-11 07:26:31.897 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file M not found.
INFO 2021-08-11 07:26:31.931 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-08-11 10:34:57.209 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-08-11 10:34:57.210 UTC: 	 Running on: Linux lxplus7107.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-11 10:34:57.210 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-11 10:34:57.210 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-08-11 10:34:57.211 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-08-11 10:34:57.211 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-08-11 10:34:57.212 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-08-11 10:34:57.264 UTC: 	 Keyboard Interrupted
INFO 2021-08-11 10:34:57.330 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-08-11 10:34:59.375 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-08-11 10:34:59.376 UTC: 	 Running on: Linux lxplus7107.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-11 10:34:59.376 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-11 10:34:59.376 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
INFO 2021-08-11 10:34:59.377 UTC: 	 Will use CRAB configuration file MWGR_crabConfig.py
DEBUG 2021-08-11 10:34:59.377 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-08-11 10:34:59.378 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-08-11 10:34:59.378 UTC: 	 Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/crab_CRUZET_344421_Prompt' already exists 
Please change the requestName in the config file
ERROR 2021-08-11 10:34:59.379 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/crab_CRUZET_344421_Prompt' already exists 
Please change the requestName in the config file
INFO 2021-08-11 10:34:59.381 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2021-08-11 13:23:31.712 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-08-11 13:23:31.713 UTC: 	 Running on: Linux lxplus758.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-11 13:23:31.713 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-11 13:23:31.713 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
DEBUG 2021-08-11 13:23:34.042 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-08-11 13:23:34.042 UTC: 	 Running on: Linux lxplus758.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-11 13:23:34.042 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-11 13:23:34.042 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fivone/.crab3
ERROR 2021-08-11 13:23:34.044 UTC: 	 CRAB configuration file M not found.
ERROR 2021-08-11 13:23:34.044 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file M not found.
INFO 2021-08-11 13:23:34.046 UTC: 	 Log file is /afs/cern.ch/user/f/fivone/Documents/NTuplizer/CRUZET/CMSSW_11_3_2/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
